spring.application.name=digikarte
server.port=8080

# --- Base de données Postgres (Heroku RDS) : utilisée en local ET en prod ---
spring.datasource.url=jdbc:postgresql://cfj13tpj5rjn9.cluster-czz5s0kz4scl.eu-west-1.rds.amazonaws.com:5432/dd6092bajr4k45?sslmode=require
spring.datasource.username=u122reqbtbg9ov
spring.datasource.password=pdc5745aad3bf8e074a496a73473628d2a7caf363edba3fffd879c318e3261c6f
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=DigiKarteSecretKey2025TresLongPourSignerLesTokensJWT
jwt.expiration-ms=86400000

# Prod Heroku : Config Var FRONTEND_URL = URL de ton frontend (ex. https://digikarte.vercel.app)
frontend.url=${FRONTEND_URL:http://localhost:3000}

# Upload photos (organisation logo, etc.) — accepter jusqu'à 15 Mo
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# Stripe (mode TEST pour le développement)
stripe.secret-key=sk_test_51TBRTBHqnjo8loIaOlzu9TcM1XQitnBbiGkzeOGCqv1L8VcCHpTI7lRoija49QKCJCOTGi7i9uTE0d1FOf5YJsbK00xOoNvq4Z
stripe.price.monthly=price_1TBRefHqnjo8loIaZ43l7AGp
stripe.price.semiannual=price_1TBRfGHqnjo8loIac6yvFcPA
stripe.price.yearly=price_1TBRfmHqnjo8loIao9kLrF29
stripe.webhook-secret=
